package com.neuedu.dao;

import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);

    int updateByMain(Product record);

    int updateBySub(Product record);

    int updateByAll(Product record);

    int updateStatus(Product record);

    List<Product> selectAllByPage(@Param("orderBy") String orderBy,
                                  @Param("pageNum") int pageNum,
                                  @Param("pageSize") int pageSize);

    int getCount();
    List<Product> selectAllByNew();
    List<Product> selectAllByHot();
    List<Product> selectAllByBanner();

    List<Product> findProductByName(@Param("name") String name,
                                    @Param("pageNum")int pageNum,
                                    @Param("pageSize")int pageSize);


    int getKeyCount(@Param("keyword") String keyword);
}